import { z } from 'zod';
import {
  BossSchema,
  CraftingStationSchema,
  CreatureSchema,
  DAMAGE_TYPES,
  FoodSchema,
  ItemSchema,
  ProgressionStepSchema,
  ResourceSchema,
  TipSchema,
  type DamageType,
} from './content-schema';
import {
  BIOME_IDS,
  BiomeRulesFileSchema,
  BiomesFileSchema,
  LOCATION_CATEGORIES,
  LocationCategoriesFileSchema,
  LocationsFileSchema,
  MetaSchema,
  SourcesFileSchema,
  WorldConstantsSchema,
} from './schema';

/** Every data file in public/data and its schema. */
export const DATA_FILES = {
  meta: MetaSchema,
  sources: SourcesFileSchema,
  world: WorldConstantsSchema,
  'biome-rules': BiomeRulesFileSchema,
  biomes: BiomesFileSchema,
  bosses: z.array(BossSchema).min(1),
  creatures: z.array(CreatureSchema).min(1),
  resources: z.array(ResourceSchema).min(1),
  items: z.array(ItemSchema).min(1),
  'crafting-stations': z.array(CraftingStationSchema).min(1),
  food: z.array(FoodSchema).min(1),
  progression: z.array(ProgressionStepSchema).min(1),
  locations: LocationsFileSchema,
  'location-categories': LocationCategoriesFileSchema,
  tips: z.array(TipSchema).min(1),
} as const;
export type DataFileName = keyof typeof DATA_FILES;
export const DATA_FILE_NAMES = Object.keys(DATA_FILES) as DataFileName[];

/** Files holding content entries (id-bearing, cross-referenced). */
const CONTENT_FILES: DataFileName[] = [
  'biomes',
  'bosses',
  'creatures',
  'resources',
  'items',
  'crafting-stations',
  'food',
  'progression',
  'locations',
  'tips',
];

export interface Issue {
  file: string;
  id?: string;
  message: string;
}

export interface TodoItem {
  file: string;
  id: string;
  path: string;
}

type Entry = Record<string, unknown> & { id: string };

const isRecord = (v: unknown): v is Record<string, unknown> =>
  typeof v === 'object' && v !== null && !Array.isArray(v);

/** Every null value inside a content entry: each one is an unverified fact. */
export function collectTodo(raw: Partial<Record<DataFileName, unknown>>): TodoItem[] {
  const out: TodoItem[] = [];
  const walk = (file: string, id: string, v: unknown, path: string) => {
    if (v === null) out.push({ file, id, path });
    else if (Array.isArray(v))
      v.forEach((x, i) => {
        walk(file, id, x, `${path}[${i}]`);
      });
    else if (isRecord(v)) {
      for (const [k, x] of Object.entries(v)) walk(file, id, x, path ? `${path}.${k}` : k);
    }
  };
  for (const file of CONTENT_FILES) {
    const arr = raw[file];
    if (!Array.isArray(arr)) continue;
    for (const e of arr) {
      if (isRecord(e) && typeof e.id === 'string') {
        // A null prefab only means "no internal name known"; it is still a TODO.
        walk(file, e.id, e, '');
      }
    }
  }
  return out;
}

export function renderDataTodo(todo: readonly TodoItem[]): string {
  const lines = [
    '# Data TODO',
    '',
    '<!-- Generated by `npm run validate:data -- --write-todo`. Do not edit by hand. -->',
    '',
    'Every `null` in `public/data/*.json` is a value we could not verify, so it is shown as',
    '"Unknown" rather than guessed (CLAUDE.md rule 3). Each needs a source before it can be',
    'filled in. During research the community wikis (valheim.fandom.com, valheim.wiki.gg,',
    'valheim.weirdgloop.org) were blocked by the network policy, so most gaps are facts that',
    'only the wikis state. See also the open verification items in `docs/SOURCES.md`.',
    '',
    `Total: ${todo.length} unverified value${todo.length === 1 ? '' : 's'}.`,
    '',
  ];
  const byFile = new Map<string, TodoItem[]>();
  for (const t of todo) byFile.set(t.file, [...(byFile.get(t.file) ?? []), t]);
  for (const [file, items] of byFile) {
    lines.push(`## ${file}.json (${items.length})`, '');
    const byId = new Map<string, string[]>();
    for (const t of items) byId.set(t.id, [...(byId.get(t.id) ?? []), t.path]);
    for (const [id, paths] of byId)
      lines.push(`- \`${id}\`: ${paths.map((p) => `\`${p}\``).join(', ')}`);
    lines.push('');
  }
  return lines.join('\n');
}

const MODIFIER_CLASS: Record<string, 'weaknesses' | 'resistances' | 'immunities' | null> = {
  slightlyWeak: 'weaknesses',
  weak: 'weaknesses',
  veryWeak: 'weaknesses',
  slightlyResistant: 'resistances',
  resistant: 'resistances',
  veryResistant: 'resistances',
  immune: 'immunities',
  normal: null,
  ignore: null,
};

export interface ValidateOptions {
  /** Only check each present file against its schema (for partial drafts). */
  schemaOnly?: boolean;
  /** Current contents of docs/DATA_TODO.md, to check it is up to date. */
  dataTodoMarkdown?: string;
}

export function validateData(
  raw: Partial<Record<DataFileName, unknown>>,
  options: ValidateOptions = {},
): Issue[] {
  const issues: Issue[] = [];
  const parsed: Partial<Record<DataFileName, unknown>> = {};

  for (const file of DATA_FILE_NAMES) {
    if (!(file in raw)) {
      if (!options.schemaOnly) issues.push({ file, message: 'file is missing' });
      continue;
    }
    const res = DATA_FILES[file].safeParse(raw[file]);
    if (res.success) {
      parsed[file] = res.data;
      continue;
    }
    for (const issue of res.error.issues) {
      const [index] = issue.path;
      const arr = raw[file];
      const entry =
        Array.isArray(arr) && typeof index === 'number' ? (arr[index] as unknown) : null;
      const id = isRecord(entry) && typeof entry.id === 'string' ? entry.id : undefined;
      issues.push({
        file,
        ...(id ? { id } : {}),
        message: `${issue.path.join('.') || '(root)'}: ${issue.message}`,
      });
    }
  }
  if (options.schemaOnly || issues.length > 0) return issues;

  const entries = (file: DataFileName): Entry[] => (parsed[file] as Entry[] | undefined) ?? [];
  const idsIn = (...files: DataFileName[]) =>
    new Set(files.flatMap((f) => entries(f).map((e) => e.id)));

  // Globally unique ids.
  const seen = new Map<string, string>();
  for (const file of CONTENT_FILES) {
    for (const e of entries(file)) {
      const prev = seen.get(e.id);
      if (prev) issues.push({ file, id: e.id, message: `id also used in ${prev}.json` });
      else seen.set(e.id, file);
    }
  }

  // Sources: registered IDs must exist.
  const sourceIds = new Set(
    (parsed.sources as { id: string }[] | undefined)?.map((s) => s.id) ?? [],
  );
  const checkSources = (file: string, id: string | undefined, sources: unknown) => {
    if (!Array.isArray(sources)) return;
    for (const s of sources) {
      if (typeof s === 'string' && s.startsWith('S-') && !sourceIds.has(s)) {
        issues.push({ file, ...(id ? { id } : {}), message: `unknown source id ${s}` });
      }
    }
  };
  for (const file of ['meta', 'world'] as const) {
    const v = parsed[file];
    if (isRecord(v)) checkSources(file, undefined, v.sources);
  }
  for (const file of ['biome-rules', 'location-categories', ...CONTENT_FILES] as DataFileName[]) {
    for (const e of (parsed[file] as Entry[] | undefined) ?? []) {
      checkSources(file, typeof e.id === 'string' ? e.id : undefined, e.sources);
    }
  }

  // Cross-references.
  const any = idsIn(...CONTENT_FILES);
  const things = idsIn('resources', 'items', 'food');
  const refs: [
    DataFileName,
    (e: Entry) => { field: string; ids: string[]; allowed: Set<string> }[],
  ][] = [];
  const recipeRefs = (e: Entry, prefix = 'recipe') => {
    const r = e.recipe as { stationId: string; materials: { itemId: string }[] } | undefined;
    if (!r) return [];
    return [
      { field: `${prefix}.stationId`, ids: [r.stationId], allowed: idsIn('crafting-stations') },
      { field: `${prefix}.materials`, ids: r.materials.map((m) => m.itemId), allowed: things },
    ];
  };
  const creaturesAndBosses = idsIn('creatures', 'bosses');
  refs.push(
    [
      'biomes',
      (e) => [
        { field: 'threats', ids: e.threats as string[], allowed: creaturesAndBosses },
        { field: 'keyResources', ids: e.keyResources as string[], allowed: things },
        {
          field: 'whatToBring',
          ids: e.whatToBring as string[],
          allowed: idsIn('resources', 'items', 'food', 'crafting-stations'),
        },
        { field: 'bossId', ids: e.bossId ? [e.bossId as string] : [], allowed: idsIn('bosses') },
      ],
    ],
    [
      'bosses',
      (e) => [
        {
          field: 'altarLocationId',
          ids: [e.altarLocationId as string],
          allowed: idsIn('locations'),
        },
        {
          field: 'summonItems',
          ids: (e.summonItems as { itemId: string }[]).map((s) => s.itemId),
          allowed: things,
        },
        {
          field: 'drops',
          ids: (e.drops as { itemId: string }[]).map((d) => d.itemId),
          allowed: things,
        },
      ],
    ],
    [
      'creatures',
      (e) => [
        {
          field: 'drops',
          ids: (e.drops as { itemId: string }[]).map((d) => d.itemId),
          allowed: things,
        },
      ],
    ],
    [
      'resources',
      (e) => [
        { field: 'droppedBy', ids: e.droppedBy as string[], allowed: creaturesAndBosses },
        ...recipeRefs(e),
      ],
    ],
    ['items', (e) => recipeRefs(e)],
    ['food', (e) => recipeRefs(e)],
    [
      'crafting-stations',
      (e) => [
        ...recipeRefs(e),
        ...(e.upgrades as Entry[]).flatMap((u, i) => recipeRefs(u, `upgrades[${i}].recipe`)),
      ],
    ],
    [
      'progression',
      (e) => [
        { field: 'bossId', ids: e.bossId ? [e.bossId as string] : [], allowed: idsIn('bosses') },
        { field: 'keyItemIds', ids: e.keyItemIds as string[], allowed: any },
      ],
    ],
    [
      'locations',
      (e) => [
        { field: 'bossId', ids: e.bossId ? [e.bossId as string] : [], allowed: idsIn('bosses') },
        {
          field: 'revealsLocationIds',
          ids: (e.revealsLocationIds as string[] | undefined) ?? [],
          allowed: idsIn('locations'),
        },
      ],
    ],
    ['tips', (e) => [{ field: 'subjectIds', ids: e.subjectIds as string[], allowed: any }]],
  );
  for (const [file, get] of refs) {
    for (const e of entries(file)) {
      for (const { field, ids, allowed } of get(e)) {
        for (const id of ids) {
          if (!allowed.has(id))
            issues.push({ file, id: e.id, message: `${field}: unknown id "${id}"` });
        }
      }
    }
  }

  // Completeness: every biome, each land biome fully described, every boss reachable.
  const biomes = entries('biomes');
  for (const id of BIOME_IDS) {
    const b = biomes.find((x) => x.id === id);
    if (!b) {
      issues.push({ file: 'biomes', id, message: 'biome entry missing' });
      continue;
    }
    if (id === 'ocean') continue;
    for (const field of ['whatToBring', 'threats', 'keyResources', 'weather'] as const) {
      if ((b[field] as unknown[]).length === 0) {
        issues.push({ file: 'biomes', id, message: `${field} must not be empty` });
      }
    }
    if (!b.bossId) issues.push({ file: 'biomes', id, message: 'bossId missing' });
  }
  const bossIds = new Set(biomes.map((b) => b.bossId).filter(Boolean));
  for (const boss of entries('bosses')) {
    if (!bossIds.has(boss.id)) {
      issues.push({ file: 'bosses', id: boss.id, message: 'no biome references this boss' });
    }
    if ((boss.summonItems as unknown[]).length === 0) {
      issues.push({ file: 'bosses', id: boss.id, message: 'summonItems must not be empty' });
    }
  }

  // A guide step names its boss and biomes in its title, so they must not be gated more
  // strictly than the step itself, or the guide leaks what the panels hide (SPEC N3).
  const levelOf = new Map<string, number>();
  for (const file of ['bosses', 'biomes'] as const) {
    for (const e of entries(file)) levelOf.set(e.id, e.spoilerLevel as number);
  }
  for (const step of entries('progression')) {
    const refs = [step.bossId, ...(step.biomeIds as string[])].filter(
      (id): id is string => typeof id === 'string',
    );
    for (const ref of refs) {
      const level = levelOf.get(ref);
      if (level !== undefined && level > (step.spoilerLevel as number)) {
        issues.push({
          file: 'progression',
          id: step.id,
          message: `spoilerLevel is below that of ${ref}`,
        });
      }
    }
  }

  // The location-category glossary explains every category exactly once (SPEC N7).
  const categoryInfo = entries('location-categories');
  for (const cat of LOCATION_CATEGORIES) {
    const n = categoryInfo.filter((c) => c.id === cat).length;
    if (n !== 1) {
      issues.push({
        file: 'location-categories',
        id: cat,
        message: n === 0 ? 'category has no glossary entry' : `category listed ${n} times`,
      });
    }
  }

  // Weaknesses/resistances must agree with the damage modifiers.
  for (const file of ['creatures', 'bosses'] as const) {
    for (const e of entries(file)) {
      const mods = e.damageModifiers as Record<DamageType, string> | null;
      if (!mods) continue;
      const expected = {
        weaknesses: [] as string[],
        resistances: [] as string[],
        immunities: [] as string[],
      };
      for (const t of DAMAGE_TYPES) {
        const cls = MODIFIER_CLASS[mods[t]];
        if (cls) expected[cls].push(t);
      }
      for (const key of ['weaknesses', 'resistances', 'immunities'] as const) {
        const got = [...(e[key] as string[])].sort().join(',');
        if (got !== [...expected[key]].sort().join(',')) {
          issues.push({ file, id: e.id, message: `${key} disagree with damageModifiers` });
        }
      }
    }
  }

  // docs/DATA_TODO.md must list exactly the current nulls.
  if (options.dataTodoMarkdown !== undefined) {
    const expected = renderDataTodo(collectTodo(raw));
    if (options.dataTodoMarkdown.trim() !== expected.trim()) {
      issues.push({
        file: 'docs/DATA_TODO.md',
        message: 'out of date: run `npm run validate:data -- --write-todo`',
      });
    }
  }
  return issues;
}
